### ISSUE TITLE
Bot not working:bug

### ISSUE THREAD

**Issue by Spry-T** [StackOverNorth/ButlerSpeak#6]
Only shows shutdown on leave and noting else

**Comment by StackOverNorth** [comment]
@Spry-T could you briefly explain what happens when you do start the bot.

**Comment by Spry-T** [comment]
When i open the bot, console opens and shows shutdown on leave and noting happens

**Comment by StackOverNorth** [comment]
I review your issue but couldn't find anything related to my bot.

Please ensure that...
- ...you have Java installed
- ...you modified the configuration file (which is created when first starting the bot) and adjusted the variables with the corresponding values. If you didn't do this, the bot is unable to connect to the server due to lack of information.

If you both ob above steps didn't work, please come back to me.

**Comment by Spry-T** [comment]
I eventually fixed it but it keep frequently disconnecting

**Comment by StackOverNorth** [comment]
> I eventually fixed it but it keep frequently disconnecting 

Are you running your bot on the same server as your TeamSpeak? If not, try using the slowmode.

**Comment by Spry-T** [comment]
Yes i am running bot in the same server as the teamspeak and yes i am using server ip as localhost but still the bot frequently disconnects

**Comment by StackOverNorth** [comment]
What features did you enable? I’ll look into it today or tomorrow.

**Comment by Spry-T** [comment]
I have enabled welcome, support, advertisement, afk feature. There should also be retry on disconnect feature build in the bot

**Comment by StackOverNorth** [comment]
I'm currently working on a new version of the bot, which will approx. be released this week. I'll add a disconnect feature too, thanks for the idea.

**Comment by Spry-T** [comment]
Also it would be great if the bot could auto add member to server group as per their time on the server like rank system and thanks for the quick response
